import Link from 'next/link'
import React from 'react'
import styles from '@/app/page.module.scss'

import { getBlogs } from '@/libs/microcms'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Home() {
  const posts = await getBlogs()

  return (
    <main className={styles.main}>
      <ul>
        {posts.contents.map((content: any) => (
          <li key={content.id}>
            <Link href={`/blog/${String(content.id)}`}>{content.title}</Link>
          </li>
        ))}
      </ul>
    </main>
  )
}
